.streamlit/secrets.toml
[api]
key = "d40k10pr01qqo3qiek8gd40k10pr01qqo3qiek90"
import streamlit as st

api_key = st.secrets["d40k10pr01qqo3qiek8gd40k10pr01qqo3qiek90"]["d40k10pr01qqo3qiek8gd40k10pr01qqo3qiek90"]
st.write("d40k10pr01qqo3qiek8gd40k10pr01qqo3qiek90")
FINNHUB_API_KEY = os.getenv("d40k10pr01qqo3qiek8gd40k10pr01qqo3qiek90")
url = f"https://finnhub.io/api/v1/quote?symbol=AAPL&token={d40k10pr01qqo3qiek8gd40k10pr01qqo3qiek90}"
 quote = requests.get(url).json()
