.streamlit/secrets.toml
[api]
key = "d40k10pr01qqo3qiek8gd40k10pr01qqo3qiek90"
import streamlit as st

api_key = st.secrets["d40k10pr01qqo3qiek8gd40k10pr01qqo3qiek90"]["d40k10pr01qqo3qiek8gd40k10pr01qqo3qiek90"]
st.write("d40k10pr01qqo3qiek8gd40k10pr01qqo3qiek90")
